title: "ASA Biopharmaceutical Section"
description: "Oncology Treatment Switch Workstream"
baseurl: "/trtswitch-website"
url: "https://shreyasreeram27.github.io"

# Build settings
markdown: kramdown
highlighter: rouge

# Kramdown settings for MathJax support
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
    preview_as_code: false


# Navigation menu items
header_pages:
  - index.md
  - objectives.md
  - methods.md
  - resources.md

# Custom variables for your site
workstream:
  title: "Oncology Treatment Switch Workstream"
  description: "Addressing the impact of treatment switch on long-term outcomes in oncology clinical trials"

# Plugins (GitHub Pages supports these automatically)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
